TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.25

  escape_vel: -0.3

  max_vel_theta: 10
  min_vel_theta: -10
  min_in_place_vel_theta: 2

  acc_lim_theta: 10
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 1.00
  
  pdist_scale: 2.25
  gdist_scale: 1.2

  holonomic_robot: false