TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  yaw_goal_tolerance: 0.56
  xy_goal_tolerance: 0.75
  latch_xy_goal_tolerance: true

  holonomic_robot: false