TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.25

  escape_vel: -0.2

  max_vel_theta: 5
  min_vel_theta: -5
  min_in_place_vel_theta: 1

  acc_lim_theta: 2.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.75

  controller_frequency: 60

  holonomic_robot: false